ada_c_old_win32:
	gprbuild --config_project=ada_c_old.gpr --config_path=configs -P../examples/first_steps/c_main
	gprbuild --config_project=ada_c_old.gpr --config_path=configs -P../examples/first_steps/ada_main