GPRBUILD=../gprbuild

ada_c_old_win32:
	$(GPRBUILD) --config=configs/ada_c_old.gpr -P../examples/first_steps/c_main
	$(GPRBUILD) --config=configs/ada_c_old.gpr -P../examples/first_steps/ada_main

vxworks6_ppc_kernel_gnat:
	$(GPRBUILD) --config=configs/vx6_ppc_kernel.cgpr -P../examples/first_steps/c_main
	$(GPRBUILD) --config=configs/vx6_ppc_kernel.cgpr -P../examples/first_steps/ada_main

