all:
	make all -C first_steps
	make all -C subsystems
	make all -C extended_projects
	make all -C ada_cpp
clean:
	make clean -C first_steps
	make clean -C subsystems
	make clean -C extended_projects
	make clean -C ada_cpp
